### ISSUE TITLE
Private album upload

### ISSUE THREAD

**Issue by alecmev** [ram-on/imgurbash2#2]
Thanks for making this script! Very handy.

I'm coming from Windows, where I've been using ShareX. It allows you to give it an Imgur access token and upload all images to a private album of your choice. I like that because then I can nuke my system and still have all uploads in one place, and have an ability to delete any one of them, at any point in the future, and I'm super used to that now.

Imgur's auth is fairly simple, AFAIK. Just gotta point your user to a certain URL, with your `client_id`, and then the user is presented with a token which they can copy and save somewhere. Choosing an album is simple too, just picking an id out of a list.

I'm thinking an API like this could work:

```bash
imgurbash2 --login # sends you to the browser and waits for token input, saves it
imgurbash2 --list-albums # lists all private albums and their ids
imgurbash2 foo.png # the usual behavior, an anonymous upload
imgurbash2 --with-auth foo.png # same upload, but with the auth headers
imgurbash2 --with-auth --album bar foo.png # upload to a private album "bar"
```

If you don't like the statefulness of storing the token somewhere, I suppose the responsibility of storing it could be shifted to the user, and you'd just take a file path as an argument.

Would you be interested in adding such functionality? Or should I go for a PR, if I want this soon?

**Comment by ram-on** [comment]
Hello @jeremejevs, i agree with the above implementation.  Feel free to submit a PR.

**Comment by laur89** [comment]
FYI I'm working on it atm (at least close to what this FR requires); expect PR soonish.
Authentication logic will be close to as it's in https://github.com/jomo/imgur-screenshot/

**Comment by laur89** [comment]
@jeremejevs - if you're on mac, could you please test the PR?
Especially when it comes to authentication bit.
